In [3]:
import pandas as pd
df = pd.read_csv('weather_2012.csv')

In [4]:
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [5]:
df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [6]:
df.sample(5)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
5529,2012-08-18 09:00:00,18.0,11.7,67,19,24.1,100.82,Mainly Clear
6515,2012-09-28 11:00:00,14.6,5.2,53,13,48.3,101.62,Mostly Cloudy
8503,2012-12-20 07:00:00,-1.8,-4.9,79,20,25.0,101.88,Cloudy
7463,2012-11-06 23:00:00,-1.5,-6.4,69,6,25.0,101.96,Clear
1835,2012-03-17 11:00:00,4.1,3.8,98,4,0.6,102.34,Fog

In [7]:
df.columns

Index(['Date/Time', 'Temp (C)', 'Dew Point Temp (C)', 'Rel Hum (%)',
       'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather'],
      dtype='object')

In [8]:
col_names1=['Date/Time', 'Temp (C)', 'Dew Point Temp (C)', 'Rel Hum (%)',
       'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather']

In [9]:
col_names=['date_time', 'temp_c', 'dew_point', 'relative_humidity', 'wind_speed', 'visibility', 'pressure', 'weather']

In [10]:
df.columns=col_names

In [11]:
df.columns

Index(['date_time', 'temp_c', 'dew_point', 'relative_humidity', 'wind_speed',
       'visibility', 'pressure', 'weather'],
      dtype='object')

In [12]:
df.mean()

/srv/conda/envs/notebook/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

temp_c                 8.798144
dew_point              2.555294
relative_humidity     67.431694
wind_speed            14.945469
visibility            27.664447
pressure             101.051623
dtype: float64

In [13]:
df.median

<bound method NDFrame._add_numeric_operations.<locals>.median of                 date_time  temp_c  dew_point  relative_humidity  wind_speed  \
0     2012-01-01 00:00:00    -1.8       -3.9                 86           4
1     2012-01-01 01:00:00    -1.8       -3.7                 87           4
2     2012-01-01 02:00:00    -1.8       -3.4                 89           7
3     2012-01-01 03:00:00    -1.5       -3.2                 88           6
4     2012-01-01 04:00:00    -1.5       -3.3                 88           7
...                   ...     ...        ...                ...         ...
8779  2012-12-31 19:00:00     0.1       -2.7                 81          30
8780  2012-12-31 20:00:00     0.2       -2.4                 83          24
8781  2012-12-31 21:00:00    -0.5       -1.5                 93          28
8782  2012-12-31 22:00:00    -0.2       -1.8                 89          28
8783  2012-12-31 23:00:00     0.0       -2.1                 86          30

      visibility  pressure               weather
0            8.0    101.24                   Fog
1            8.0    101.24                   Fog
2            4.0    101.26  Freezing Drizzle,Fog
3            4.0    101.27  Freezing Drizzle,Fog
4            4.8    101.23                   Fog
...          ...       ...                   ...
8779         9.7    100.13                  Snow
8780         9.7    100.03                  Snow
8781         4.8     99.95                  Snow
8782         9.7     99.91                  Snow
8783        11.3     99.89                  Snow

[8784 rows x 8 columns]>

In [14]:
df.mode()

,date_time,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure,weather
0,2012-01-01 00:00:00,16.6,-0.9,68.0,9.0,25.0,101.13,Mainly Clear
1,2012-01-01 01:00:00,NaN,12.9,NaN,NaN,NaN,NaN,NaN
2,2012-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2012-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2012-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8780,2012-12-31 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8781,2012-12-31 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8782,2012-12-31 22:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8783,2012-12-31 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.count

<bound method DataFrame.count of                 date_time  temp_c  dew_point  relative_humidity  wind_speed  \
0     2012-01-01 00:00:00    -1.8       -3.9                 86           4
1     2012-01-01 01:00:00    -1.8       -3.7                 87           4
2     2012-01-01 02:00:00    -1.8       -3.4                 89           7
3     2012-01-01 03:00:00    -1.5       -3.2                 88           6
4     2012-01-01 04:00:00    -1.5       -3.3                 88           7
...                   ...     ...        ...                ...         ...
8779  2012-12-31 19:00:00     0.1       -2.7                 81          30
8780  2012-12-31 20:00:00     0.2       -2.4                 83          24
8781  2012-12-31 21:00:00    -0.5       -1.5                 93          28
8782  2012-12-31 22:00:00    -0.2       -1.8                 89          28
8783  2012-12-31 23:00:00     0.0       -2.1                 86          30

      visibility  pressure               weather
0            8.0    101.24                   Fog
1            8.0    101.24                   Fog
2            4.0    101.26  Freezing Drizzle,Fog
3            4.0    101.27  Freezing Drizzle,Fog
4            4.8    101.23                   Fog
...          ...       ...                   ...
8779         9.7    100.13                  Snow
8780         9.7    100.03                  Snow
8781         4.8     99.95                  Snow
8782         9.7     99.91                  Snow
8783        11.3     99.89                  Snow

[8784 rows x 8 columns]>

In [16]:
df['temp_f'] = df.apply(lambda x: (9/5)*x['temp_c']+32,axis=1)
print(df)

                date_time  temp_c  dew_point  relative_humidity  wind_speed  \
0     2012-01-01 00:00:00    -1.8       -3.9                 86           4
1     2012-01-01 01:00:00    -1.8       -3.7                 87           4
2     2012-01-01 02:00:00    -1.8       -3.4                 89           7
3     2012-01-01 03:00:00    -1.5       -3.2                 88           6
4     2012-01-01 04:00:00    -1.5       -3.3                 88           7
...                   ...     ...        ...                ...         ...
8779  2012-12-31 19:00:00     0.1       -2.7                 81          30
8780  2012-12-31 20:00:00     0.2       -2.4                 83          24
8781  2012-12-31 21:00:00    -0.5       -1.5                 93          28
8782  2012-12-31 22:00:00    -0.2       -1.8                 89          28
8783  2012-12-31 23:00:00     0.0       -2.1                 86          30

      visibility  pressure               weather  temp_f
0            8.0    101.24                   Fog   28.76
1            8.0    101.24                   Fog   28.76
2            4.0    101.26  Freezing Drizzle,Fog   28.76
3            4.0    101.27  Freezing Drizzle,Fog   29.30
4            4.8    101.23                   Fog   29.30
...          ...       ...                   ...     ...
8779         9.7    100.13                  Snow   32.18
8780         9.7    100.03                  Snow   32.36
8781         4.8     99.95                  Snow   31.10
8782         9.7     99.91                  Snow   31.64
8783        11.3     99.89                  Snow   32.00

[8784 rows x 9 columns]

In [17]:
df=df[['date_time','temp_f','temp_c','dew_point','relative_humidity','wind_speed','visibility','pressure','weather']]

In [18]:
df.head()

,date_time,temp_f,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure,weather
0,2012-01-01 00:00:00,28.76,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,28.76,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,28.76,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,29.30,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,29.30,-1.5,-3.3,88,7,4.8,101.23,Fog

In [19]:
df.dtypes

date_time             object
temp_f               float64
temp_c               float64
dew_point            float64
relative_humidity      int64
wind_speed             int64
visibility           float64
pressure             float64
weather               object
dtype: object

In [20]:
df.date_time = pd.to_datetime(df.date_time)

In [21]:
df.dtypes

date_time            datetime64[ns]
temp_f                      float64
temp_c                      float64
dew_point                   float64
relative_humidity             int64
wind_speed                    int64
visibility                  float64
pressure                    float64
weather                      object
dtype: object

In [22]:
df.head()

,date_time,temp_f,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure,weather
0,2012-01-01 00:00:00,28.76,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,28.76,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,28.76,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,29.30,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,29.30,-1.5,-3.3,88,7,4.8,101.23,Fog

In [23]:
df.date_time.dt.month

0        1
1        1
2        1
3        1
4        1
        ..
8779    12
8780    12
8781    12
8782    12
8783    12
Name: date_time, Length: 8784, dtype: int64